export const faqs = [
  {
    question: 'Who is UNUVIA for?',
    answer:
      'Students, faculty, researchers and university staff. You can sign up with any email address; a university email is optional.',
  },
  {
    question: 'What can I use today?',
    answer:
      'Ask questions, attach documents or extract text from images, and save conversations in this browser. Answers are generated by Claude, from Anthropic.',
  },
  {
    question: 'What does the Free plan include?',
    answer:
      'Your personal workspace, browser history, document attachments and Claude Haiku 5.5, within a daily usage allowance. No credit card is needed.',
  },
  {
    question: 'Can I subscribe to Pro now?',
    answer:
      'Open your account’s Plan tab to check payment availability and your local price. Pay using the provided instructions, then submit your transaction reference. Pro starts after an administrator verifies the payment, for 30 days, with no automatic renewal.',
  },
  {
    question: 'Where are my conversations stored?',
    answer:
      'In this browser, separately for each account. History does not sync across devices. Your message and attached text are sent to Anthropic’s Claude API when you ask for a response.',
  },
  {
    question: 'Can my team use UNUVIA?',
    answer:
      'Contact us for a custom proposal. Shared workspaces, organization controls and integrations are planned; they are not included in Free today.',
  },
];
export const useCases = [
  {
    name: 'Learning',
    icon: 'school',
    role: 0,
    title: 'Understand your course material.',
    description:
      'Get an explanation, make a study guide from your notes or practice with questions.',
    prompt:
      'Explain the greenhouse effect with a simple example, then ask me three practice questions.',
    points: [
      'Explain unfamiliar concepts',
      'Structure your study notes',
      'Practice with useful questions',
    ],
  },
  {
    name: 'Teaching',
    icon: 'book',
    role: 1,
    title: 'Prepare your next lesson.',
    description:
      'Draft a lesson outline, plan an activity or prepare exercises. Review and adapt the material for your students.',
    prompt:
      'Help me outline a 45-minute lesson on critical thinking with learning objectives and a group activity.',
    points: ['Build lesson outlines', 'Explore classroom activities', 'Draft practice questions'],
  },
  {
    name: 'Research',
    icon: 'flask',
    role: 2,
    title: 'Organize your research.',
    description:
      'Outline a research question, compare your documents or prepare a literature review. Check the sources before using the results.',
    prompt:
      'Help me structure a literature review on urban biodiversity. Identify research questions and gaps to investigate.',
    points: [
      'Frame research questions',
      'Compare your text documents',
      'Organize an initial outline',
    ],
  },
  {
    name: 'Writing',
    icon: 'file',
    role: 3,
    title: 'Write and revise your documents.',
    description:
      'Turn your notes into a brief, summary or report, then revise the structure and wording.',
    prompt: 'Help me turn these notes into a clear project brief: ',
    points: ['Draft reports and briefs', 'Summarize source material', 'Refine tone and structure'],
  },
];
